Fazer install e load packages

```{r, results='hide', warning = FALSE, message=FALSE}

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install(c(
  "TCGAbiolinks",
  "DESeq2",
  "Biobase",
  "genefilter",
  "pheatmap",
  "org.Hs.eg.db",
  "fgsea",
  "SummarizedExperiment",
  "Glimma",
  "edgeR",
  "AnnotationDbi"
))

install.packages(c(
  "jpeg",
  "ggbeeswarm",
  "ggplot2",
  "xfun",
  "factoextra",
  "Rtsne",
  "gplots",
  "RColorBrewer",
  "tidyverse",
  "rpart",
  "rsample",
  "caret"
))

```

Load Packages
```{r,results='hide', warning = FALSE, message=FALSE}
library(BiocManager)
library(jpeg)
library(TCGAbiolinks)
library(Biobase)
library(DESeq2)
library(ggbeeswarm)
library(genefilter)
library(pheatmap)
library(org.Hs.eg.db)
library(fgsea)
library(ggplot2)
library(xfun)
library(SummarizedExperiment) 
library(factoextra)
library(Rtsne)
library(gplots)
library(edgeR)
library(AnnotationDbi)
library(RColorBrewer)
library(tidyverse)
library(rpart)
library(rsample)
library(caret)
```

Download dos dados para directoria desejada:
```{r, message = FALSE}

# query_LUAD <- GDCquery(
#   project = "TCGA-LUAD",
#   data.category = "Transcriptome Profiling",
#   data.type = "Gene Expression Quantification",
#   workflow.type = "STAR - Counts"
# )
# 
# GDCdownload(query = query_LUAD, directory = "/home/arog/Documents/2_semestre/ECDB/project_data/GDCdata")
# 
# rna_seq_LUAD <- GDCprepare(
#   query = query_LUAD,
#   save = TRUE,
#   save.filename = "/home/arog/Documents/2_semestre/ECDB/project_data/mRNA_TCGA-LUAD.rda",
#   directory = "/home/arog/Documents/2_semestre/ECDB/project_data/GDCdata"
# )

rna_seq_LUAD = get(
  load("/home/arog/Documents/2_semestre/ECDB/project_data/mRNA_TCGA-LUAD.rda")
  )
```



